'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Strings

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VGTTutorial.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to We have created a plane normal to the satellite&apos;s velocity vector, with the satellite&apos;s center point as the start location and a displacement vector to Earth as a reference.  Click &quot;Create Angle&quot; in order to display the angles between the VGT components we have displayed thus far..
        '''</summary>
        Friend Shared ReadOnly Property CreateAngles() As String
            Get
                Return ResourceManager.GetString("CreateAngles", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to VGT can provide user defined &quot;Templates&quot;.  Once a template is defined (such as our Velocity Vector) every object of the same type created after it will contain the same vector, plane, point, axes, angle, or system.  Click &quot;Create Axes&quot; to show a predefined Axes..
        '''</summary>
        Friend Shared ReadOnly Property CreateAxes() As String
            Get
                Return ResourceManager.GetString("CreateAxes", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Here we have displayed the &quot;Vehicle Velocity Local Horizontal&quot; (VVLH(Earth)) template to demonstrate Axes.  Axes can be based on vectors, central bodies, axes, points, and a variety of other components.  Please click &quot;Create Plane&quot;..
        '''</summary>
        Friend Shared ReadOnly Property CreatePlane() As String
            Get
                Return ResourceManager.GetString("CreatePlane", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Now that we have loaded our control, we will create a satellite and facility for our demonstration.  Please click &quot;Create Satellite&quot;..
        '''</summary>
        Friend Shared ReadOnly Property CreateSatellite() As String
            Get
                Return ResourceManager.GetString("CreateSatellite", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to We have created a satellite and facility.  Let&apos;s demonstrate the vector geometry tool&apos;s ability to display vectors and calculations regarding STK objects.  We will display the distance to the facility in &quot;km&quot;.  Click &quot;Create Vector&quot; to create a Displacement vector to accessFac.  The magnitude (or distance) will be displayed..
        '''</summary>
        Friend Shared ReadOnly Property CreateVector() As String
            Get
                Return ResourceManager.GetString("CreateVector", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to As you can see, we have created three angles referencing &quot;NormalPlane&quot;, the velocity vector, and the distance vector to our accessFac.  By clicking &quot;Play&quot; in the upper left hand corner, you will be able to see the angles and vectors automatically adjust as the satellite makes its rotation around the central body Earth..
        '''</summary>
        Friend Shared ReadOnly Property Finish() As String
            Get
                Return ResourceManager.GetString("Finish", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to We have created a vector from the center of the our Satellite to accessFac.  Let&apos;s display the velocity vector that comes as a standard template to VGT satellite objects. Click &quot;Show Velocity Vector&quot;..
        '''</summary>
        Friend Shared ReadOnly Property ShowVelocityVector() As String
            Get
                Return ResourceManager.GetString("ShowVelocityVector", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Welcome to AGI&apos;s tutorial for VGT. In this tutorial, we will show the basics of VGT (Vector Geometry Tool). Please click &quot;New Scenario&quot; to get started..
        '''</summary>
        Friend Shared ReadOnly Property Welcome() As String
            Get
                Return ResourceManager.GetString("Welcome", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
