#if !defined(AFX_AGDRAWELEM_H__74216932_BF92_4F2B_8B4D_F6FC76A31820__INCLUDED_)
#define AFX_AGDRAWELEM_H__74216932_BF92_4F2B_8B4D_F6FC76A31820__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgDrawElem wrapper class

class CAgDrawElem : public COleDispatchDriver
{
public:
	CAgDrawElem() {}		// Calls COleDispatchDriver default constructor
	CAgDrawElem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgDrawElem(const CAgDrawElem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGDRAWELEM_H__74216932_BF92_4F2B_8B4D_F6FC76A31820__INCLUDED_)
