// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgExecCmdResult wrapper class

class CAgExecCmdResult : public COleDispatchDriver
{
public:
	CAgExecCmdResult() {}		// Calls COleDispatchDriver default constructor
	CAgExecCmdResult(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgExecCmdResult(const CAgExecCmdResult& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CString GetItem(long Index);
	LPUNKNOWN Get_NewEnum();
	// method 'Range' not emitted because of invalid return type or parameter type
};
