#if !defined(AFX_AGOBJPATHCOLLECTION_H__1168196B_65FA_4767_9684_C0C0D178C786__INCLUDED_)
#define AFX_AGOBJPATHCOLLECTION_H__1168196B_65FA_4767_9684_C0C0D178C786__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgObjPathCollection wrapper class

class CAgObjPathCollection : public COleDispatchDriver
{
public:
	CAgObjPathCollection() {}		// Calls COleDispatchDriver default constructor
	CAgObjPathCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgObjPathCollection(const CAgObjPathCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CString GetItem(long Index);
	LPUNKNOWN Get_NewEnum();
	// method 'Range' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGOBJPATHCOLLECTION_H__1168196B_65FA_4767_9684_C0C0D178C786__INCLUDED_)
