// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgPickInfoData wrapper class

class CAgPickInfoData : public COleDispatchDriver
{
public:
	CAgPickInfoData() {}		// Calls COleDispatchDriver default constructor
	CAgPickInfoData(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgPickInfoData(const CAgPickInfoData& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetObjPath();
	double GetLat();
	double GetLon();
	double GetAlt();
	BOOL GetIsObjPathValid();
	BOOL GetIsLatLonAltValid();
};
