#if !defined(AFX_AGRUBBERBANDPICKINFODATA_H__9B1E9D7F_DCB3_4A4B_BD5B_1B33FBED6EF8__INCLUDED_)
#define AFX_AGRUBBERBANDPICKINFODATA_H__9B1E9D7F_DCB3_4A4B_BD5B_1B33FBED6EF8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAgObjPathCollection;

/////////////////////////////////////////////////////////////////////////////
// CAgRubberBandPickInfoData wrapper class

class CAgRubberBandPickInfoData : public COleDispatchDriver
{
public:
	CAgRubberBandPickInfoData() {}		// Calls COleDispatchDriver default constructor
	CAgRubberBandPickInfoData(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgRubberBandPickInfoData(const CAgRubberBandPickInfoData& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAgObjPathCollection GetObjPaths();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGRUBBERBANDPICKINFODATA_H__9B1E9D7F_DCB3_4A4B_BD5B_1B33FBED6EF8__INCLUDED_)
