// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAgExecCmdResult;

/////////////////////////////////////////////////////////////////////////////
// CAgSTKXApplication wrapper class

class CAgSTKXApplication : public COleDispatchDriver
{
public:
	CAgSTKXApplication() {}		// Calls COleDispatchDriver default constructor
	CAgSTKXApplication(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgSTKXApplication(const CAgSTKXApplication& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAgExecCmdResult ExecuteCommand(LPCTSTR Command);
	BOOL GetEnableConnect();
	void SetEnableConnect(BOOL bNewValue);
	short GetConnectPort();
	void SetConnectPort(short nNewValue);
	CString GetHostID();
	CString GetRegistrationID();
	CString GetVersion();
	CString GetLicensingReport();
	void SetVendorID(LPCTSTR lpszNewValue);
	CString GetVendorID();
	BOOL SetOnlineOptions(BOOL UseProxy, LPCTSTR ServerName, long PortNum, LPCTSTR UserName, LPCTSTR Password, BOOL SavePassword);
	BOOL GetOnlineOptions(BOOL* UseProxy, BSTR* ServerName, long* PortNum, BSTR* UserName);
	CString GetLogFileFullName();
	long GetLoggingMode();
	void SetLoggingMode(long nNewValue);
	long GetConnectMaxConnections();
	void SetConnectMaxConnections(long nNewValue);
};
