#if !defined(AFX_AGUIAXVOCNTRL_H__6B1E0153_4C8B_45DD_B1A2_D00533C2FEC8__INCLUDED_)
#define AFX_AGUIAXVOCNTRL_H__6B1E0153_4C8B_45DD_B1A2_D00533C2FEC8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;
class CAgPickInfoData;
class CAgSTKXApplication;
class CAgRubberBandPickInfoData;
class CAgDrawElemCollection;

/////////////////////////////////////////////////////////////////////////////
// CAgUiAxVOCntrl wrapper class

class CAgUiAxVOCntrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAgUiAxVOCntrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa82e9a8, 0x53, 0x4e51, { 0x91, 0x82, 0x64, 0xe6, 0xb5, 0xd6, 0xd0, 0xbc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetRefPicture(LPDISPATCH newValue);
	void SetPicture(LPDISPATCH newValue);
	CPicture GetPicture();
	CAgPickInfoData PickInfo(long x, long y);
	long GetWinID();
	void SetWinID(long nNewValue);
	CAgSTKXApplication GetApplication();
	void ZoomIn();
	BOOL GetNoLogo();
	void SetNoLogo(BOOL bNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	void SetVendorID(LPCTSTR lpszNewValue);
	CString GetVendorID();
	CAgRubberBandPickInfoData RubberBandPickInfo(long Left, long Top, long Right, long Bottom);
	long GetMouseMode();
	void SetMouseMode(long nNewValue);
	CAgDrawElemCollection GetDrawElements();
	BOOL GetPptPreloadMode();
	void SetPptPreloadMode(BOOL bNewValue);
	BOOL GetAdvancedPickMode();
	void SetAdvancedPickMode(BOOL bNewValue);
	void CopyFromWinID(long WinID);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGUIAXVOCNTRL_H__6B1E0153_4C8B_45DD_B1A2_D00533C2FEC8__INCLUDED_)
